package Vista;

import Controlador.PhoneLogic;
import Modelo.Contact;
import Modelo.Phone;
import javax.swing.JOptionPane;

public class phoneFrame extends javax.swing.JFrame {
    PhoneLogic pLogic;
    ConcactList2 cList;
    /**
     * Creates new form phoneFrame
     */
    public phoneFrame(ConcactList2 cList) {
        initComponents();
        this.pLogic = new PhoneLogic();
        this.cList = cList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tipoTbox = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        ladaTbox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numTbox = new javax.swing.JTextField();
        pAcceptBtn = new javax.swing.JButton();
        pCancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(224, 219, 216));

        jLabel1.setBackground(new java.awt.Color(224, 219, 216));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingresa el tipo de numero");

        label.setBackground(new java.awt.Color(224, 219, 216));
        label.setForeground(new java.awt.Color(0, 0, 0));
        label.setText("Ingresa la lada del numero (ejemplo: +52)");

        jLabel3.setBackground(new java.awt.Color(224, 219, 216));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingresa el numero");

        pAcceptBtn.setText("Aceptar");
        pAcceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAcceptBtnActionPerformed(evt);
            }
        });

        pCancelBtn.setText("Cancelar");
        pCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pAcceptBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pCancelBtn)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoTbox)
                    .addComponent(ladaTbox)
                    .addComponent(jLabel3)
                    .addComponent(numTbox, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ladaTbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numTbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pAcceptBtn)
                    .addComponent(pCancelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pAcceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAcceptBtnActionPerformed
        Phone p = new Phone(
                numTbox.getText(),
                ladaTbox.getText(), 
                tipoTbox.getText()
        );
        
        try{
            this.pLogic.check(p);
            this.
            cList.getLastContactSel().getPhones().add(p);
            cList.loadPhones(cList.getLastContactSel().getPhones());
            JOptionPane.showMessageDialog(null, "Se agregó el número correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.hide();
            this.resetForm();
        }catch(Exception e){
            System.out.println(e.getStackTrace());
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_pAcceptBtnActionPerformed

    private void pCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pCancelBtnActionPerformed
        this.hide();
        this.resetForm();
    }//GEN-LAST:event_pCancelBtnActionPerformed

    private void resetForm(){
        this.ladaTbox.setText("");
        this.numTbox.setText("");
        this.tipoTbox.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JTextField ladaTbox;
    private javax.swing.JTextField numTbox;
    private javax.swing.JButton pAcceptBtn;
    private javax.swing.JButton pCancelBtn;
    private javax.swing.JTextField tipoTbox;
    // End of variables declaration//GEN-END:variables
}
